apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "booking.name" . }}-migrate
  labels:
    {{- include "booking.labels" . | nindent 4 }}
    component: migrate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "booking.selectorLabels" . | nindent 8 }}
        component: migrate
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: {{ include "booking.name" . }}-config
            - secretRef:
            name: {{ include "booking.name" . }}-secret
          command:
            - sh
            - -c
            - |
            until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME"; do
            echo "waiting for postgres..."
            sleep 3
            done
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "src/db/migrate.js"]
          envFrom:
            - configMapRef:
                name: {{ include "booking.name" . }}-config
            - secretRef:
            name: {{ include "booking.name" . }}-secret
