apiVersion: v1
kind: Service
metadata:
  name: {{ include "booking.name" . }}-backend
  labels:
    {{- include "booking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "booking.selectorLabels" . | nindent 4 }}
    component: backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP